### ISSUE TITLE
Update installation instructions to include a Docker container configuration usage

### ISSUE THREAD

**Issue by Nemo1369** [GolosChain/wiki#20]
Install instructions need to be updated to include Docker-container usage.

Release: docker run -p 8090:8090 -p 2001:2001 -it -v chain_data:/var/lib/golosd goloschain/golos
Testnet: docker run -p 8092:8090 -p 2002:2001 -e STEEMD_WITNESS_NAME="cyberfounder" -e STEEMD_EXTRA_OPTS="--enable-stale-production" -e STEEMD_MINER_NAME="cyberfounder" -e STEEMD_PRIVATE_KEY="5JVFFWRLwz6JoP9kguuRFfytToGU6cLgBVTL9t6NB3D3BQLbUBS" -e STEEMD_MINING_THREADS=4 -v testnet_chain_data:/var/lib/golosd -it goloschain/golos_testnet:0.17.0

**Comment by vadbars** [comment]
"--enable-stale-production" не опечатка ли? 
--enable-sta**b**le-production

**Comment by testzcrypto** [comment]
Нет, это не опечатка, правильно **--enable-stale-production**
PS: stale - несвежий

**Comment by vadbars** [comment]
Добавил https://wiki.golos.io/3-guides/ubuntu_guide.html#использование-контейнеров-docker
