### ISSUE TITLE
Распилить раздел "Разработчикам"

### ISSUE THREAD

**Issue by bitfag** [GolosChain/wiki#24]
Предлагаю раздел "разработчикам" распилить на несколько. Как минимум, выделить отдельный раздел "Администрирование golosd". А лучше:

* Администрирование golosd
* Разработка приложений на блокчейне Голос
* Разработка golosd

Разработка golosd - тут про внутреннюю кухню golosd, и т.п.

**Comment by vadbars** [comment]
associated with #27

**Comment by bitfag** [comment]
Какие-то движения планируются по этому вопросу?

**Comment by vadbars** [comment]
Владимир, готовы сделать пуллреквест?

**Comment by bitfag** [comment]
Попробую заняться этим на неделе.
