### ISSUE TITLE
Нужна тотальная реорганизация wiki

### ISSUE THREAD

**Issue by bitfag** [GolosChain/wiki#25]
wiki сейчас представляет собой большую помойку из копипасты статей разной степени протухлости. 

Предложения:

1. Прекратить практику прямого копипаста.
1. Переписать статьи таким образом, чтобы они не были написаны от первого лица.
1. Пересмотреть оглавление, не допускать дублирования одной и той же темы в разных статьях.
1. Всё тухлое перенести в отдельный раздел "протухло" чтобы старьё не мозолило глаза и не пересекалось с актуальными данными.

**Comment by vadbars** [comment]
Хороший план. 
1. Это компромисс. Пару месяцев назад не было и этого. Тексты терялись на сайте. Так они хотя бы собраны в одном месте.
2. Сохранение авторства дает хотя бы какой-то мотив участия в наполнении вики. Но по мере накопления материала его можно перерабатывать и обобщать, устраняя дублирование. Это можно начинать сейчас, вы правы. Делайте пул реквесты.
3. Следует на предыдущим пунктом. Появятся обобщающие статьи, изменим оглавление.
4. Да, довольно много устаревших материалов. Часть можно безболезненно удалить, часть нужно оставить как историю steem/golos. Отмечайте устаревшее в ишью.

**Comment by bitfag** [comment]
OK.

2. Авторы вообще не участвуют в наполнении wiki, в 2017-м году ни одного PR, у них нет мотивации.

**Comment by vadbars** [comment]
divided into issues #28  #27
