### ISSUE TITLE
Create Release Notes for HF 18

### ISSUE THREAD

**Issue by marijadia** [GolosChain/wiki#59]
1. create a short list of features with descriptions in English
2. create a full description of new HF 18 functionality in Russian for the wiki.golos.io

**Comment by anazarov79** [comment]
The first version (draft) of Release Notes in English is ready to review.

**Comment by anazarov79** [comment]
Completed version for HF18_Release_Notes is posed on:
 https://github.com/GolosChain/golos/releases
The task finished.

**Comment by anazarov79** [comment]
started work : HF 18 functionality in Russian

**Comment by anazarov79** [comment]
Both versions of Release Notes in engl. and in russia are completely done.
