### ISSUE TITLE
Перевод и доработка билд-инструкции

### ISSUE THREAD

**Issue by marijadia** [GolosChain/wiki#61]
У нас есть инструкция https://github.com/GolosChain/golos/wiki/Build-instruction 
Необходимо перевести ее на русский и дополнить следующей информацией: 
1. какие библиотеки нужны для сборки. Если они меняются от версии к версии, то нужно добавить памятку о необходимости учесть новые версии библиотек.
2. Добавить информацию о более простых способах для обновления (для не Линуксоидов), например 
https://golos.io/golosnode/@ruslan/podnyatie-nody-dlya-golosa-odnoi-strokoi
3. Описать как проводится реплей, что нужно делать
4. Добавить информацию про shared_memory файл.
5. Добавить информацию о разнице между разными типами нод и есть ли отличия в их установке/обновлении?

PS. возможно так же стоит добавить информацию какие плаги включены в разные ноды, для чего эти плагины нужны и как их включать/выключать.

**Comment by anazarov79** [comment]
Информация полезная, но требуется хорошенько обдумать, где и как ее разместить, чтобы не ввести в заблуждение пользователя.

**Comment by anazarov79** [comment]
Есть стандартная типовая структура документа инструкции и хотелось бы ее придерживаться.

## Шаблон инструкции по установке GolosChain

### АННОТАЦИЯ
Указать назначение Инструкции.
Указать категорию лиц, для которой Инструкция может являться полезной для прочтения.

### 1_ОБЩИЕ СВЕДЕНИЯ
1.1_Назначение GolosChain. Область применения.
1.2_Перечень выполняемых функций.
1.3_Отличие новой версии GolosChain от предыдущих. Перечень новых возможностей и устраненных недостатков.
1.4_Требования к аппаратным средствам и ПО. Привести рекомендуемые характеристики применительно к системному ПО, дополнительному программному окружению.

### 2_УСТАНОВКА И НАСТРОЙКА
2.1_Рекомендации по выполнению. Что сконфигурировать,что открыть, куда войти, чему следовать. Указать подразделы, с которых следует начать установку как с «нуля», так и для обновления.
2.2_Последовательность операций. Привести выполняемые команды (вид команды, скриншоты). Указать ожидаемый результат для каждой выполняемой команды.
2.3_Установить значения необходимых параметров.

### 3_ПРОВЕРКА УСТАНОВКИ
Указать действия, выполнения и получаемые результаты которых гарантируют правильную установку новой версии GolosChain.

4_ПЕРЕЧЕНЬ ВОЗМОЖНЫХ СООБЩЕНИЙ, ПОЛУЧАЕМЫХ ОПЕРАТОРОМ
Привести в табличном виде основные сообщения (предупреждения, ошибки), появление которых возможно на мониторе оператора в процессе установки. Указать причину их появления и рекомендации по их устранению.

**Comment by anazarov79** [comment]
Составление русскоязычной версии "Руководства по установке" закончено.
https://wiki.golos.io/golosd/HardFork/HF18_BuildInstruction-rus.html
Документ составлен с учетом требований, приведенных в задании, и согласован с руководителем разработки. Исключение составило требование (в форме P.S.) к информации о плагинах. Это требование важное, но не может быть размещено в этом документе, так как не относится к установке блокчейна. Информация о плагинах будет размещена в другом документе.
