### ISSUE TITLE
Описание взаимосвязи токенов GBG и Голос

### ISSUE THREAD

**Issue by marijadia** [GolosChain/wiki#63]
Поискать в Вики уже существующие статье на тему механики работы этих токенов.
Описать как курсы токенов зависят друг от друга.

**Comment by anazarov79** [comment]
Вадим предоставил краткую информацию о сути предложения, поступившего со стороны делегатов, а также акцентировал внимание на возможные риски в случае реализации этого предложения.

**Comment by anazarov79** [comment]
В wiki добавлена статья "Риски увеличения отклонения токена GBG от его номинальной стоимости"
https://wiki.golos.io/golosd/mix/riski-izmenenija-GBG.html
